### ISSUE TITLE
Notification color and icon

### ISSUE THREAD

**Issue by FrederickKDP** [DrMoriarty/nativelib#5]
Hi,
I have been wondering, is changing color and/or icon possible? I'm not necessarily asking the feature, just asking your thoughts about it.
I would gladly collaborate with the tool, but I'm very inexperienced, so I'm not sure how to do it. From what I've been reading, it might be possible by changing the Android Manifest, but it doesn't seem to be enough. So I'm stuck on this part.

Thank you for the attention

**Comment by DrMoriarty** [comment]
Hello!
The plugin uses app icon for showing notification. Usually on Android this icon considered as monochrome mask with alpha channel. So it is turning in red square.
I'm thinking about setting custom icon for notifications but I don't know a comfortable way to set an additional icon for application in Godot.

What about color, I can make new method for changing default notification color. Of course it will work only for android.

**Comment by FrederickKDP** [comment]
Just Android sounds good for me! If you can, that would be awesome!
In the meantime, if adding the option within Godot is complicated, if I may, would you have any leads of how to add it separately?
As I mentioned before, I always feel very awkward asking for features. If I can help anyhow or get around it, please let me know

**Comment by DrMoriarty** [comment]
@FrederickKDP Hi!
I just released local notification plugin v0.2.0 with ability to customize notification icon and color. See https://github.com/DrMoriarty/godot-local-notification/blob/master/README.md

**Comment by FrederickKDP** [comment]
Wow! You're hero!
I was about to say that I finished a project for mobile a while ago, it'll be to great use!
Thanks a ton!

**Comment by TIBI4** [comment]
@DrMoriarty 
> I just released local notification plugin v0.2.0 with ability to customize notification icon and color. See https://github.com/DrMoriarty/godot-local-notification/blob/master/README.md

I have been testing adding a **notification_icon.png** with those dimensions you told him into **android\build\res\mipmap...** and it's not working for [**godot-firebase-cloudmessaging**](https://github.com/DrMoriarty/godot-firebase-cloudmessaging), that is the same thing but for remote notifications.

Maybe you forgot to do the same for that 2nd repository? 

_**Thanks for your time!**_

**Comment by DrMoriarty** [comment]
Firebase's notifications have made by different way in comparison with local-notification plugin. I'm not sure if we could change some settings of it. I should check the documentation.

**Comment by TIBI4** [comment]
I was using another "plugin" (I don't even know how to call it) from another person, but it wasn't so easy to use. This same problem I described above happened too with that other's guy plugin, and I wanted to use my own fancy icon. Then, digging through the web, I found a way to do this, so this should doable here too AFAIK.

I'm not so fast doing things when I have to compile outside Godot, and sometimes I don't even know what I'm doing, but I can tell you that maybe soon I will tell you/send a PR to the repository unless you do it first.

**Comment by TIBI4** [comment]
Hey, @DrMoriarty. I made it work without having to compile anything. And for people struggling with this same problem, read the next steps **carefully**.

1) Complete [NativeLib FCM](https://github.com/DrMoriarty/godot-firebase-cloudmessaging) setup, so your notifications will show up without your desired "notification_icon.png" but a white square ot something you didn't want.

2) Add the white notification icon **notification_icon.png** under **_yourgodotproject_/android/build/res/mipmap/**.

3) In the **AndroidManifest.xml** under **_yourgodotproject_/android/build/** inside **<application>**:
`<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/notification_icon" />`

This may help, and I think you can work from this in order to make a more user friendly way to do this.

**Comment by DrMoriarty** [comment]
@TIBI4 Great!
I will add this steps to README file.
As for more user friendly way, I can write a hook for copying custom icon files to android/build folder but automate working with AndroidManifest.xml can be tricky. Usually it edited by Godot and sometimes changes may be lost or broken.

Another way: I can add `meta-data` tag into plugin's AndoroidManifest and put some placeholders for notification icons into the plugin archive (they will be installed in the right place). And then user can replace them when he/she wants.

What do you think?

**Comment by TIBI4** [comment]
> What do you think?

I think those are both good ideas!
